<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ReadingsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('readings')->delete();

        \DB::table('readings')->insert([
            0 => [
                'id' => 1,
                'title' => 'Apostles\' Creed',
                'type' => 'creed',
                'text' => '<h3>Congregation</h3><p>I believe in God, the Father Almighty, the Creator of heaven and earth, and in Jesus Christ, His only Son, our Lord: Who was conceived of the Holy Spirit, born of the Virgin Mary, suffered under Pontius Pilate, was crucified, died, and was buried. He descended into hell. The third day, He arose again from the dead. He ascended into heaven, and sits at the right hand of God the Father Almighty, whence He shall come to judge the living and the dead.</p><p>I believe in the Holy Spirit, the holy catholic church, the communion of saints, the forgiveness of sins, the resurrection of the body, and life everlasting. Amen.</p>',
                'created_at' => '2025-06-04 03:03:12',
                'updated_at' => '2025-07-05 18:30:07',
            ],
            1 => [
                'id' => 2,
                'title' => 'Nicene Creed',
                'type' => 'creed',
                'text' => '<h3>Congregation</h3><p>We believe in one God, the Father, the Almighty, maker of heaven and earth, of all that is, seen and unseen.</p><p>We believe in one Lord, Jesus Christ, the only Son of God, eternally begotten of the Father, God from God, Light from Light, true God from true God, begotten, not made, of one Being with the Father.&nbsp; Through him all things were made.&nbsp; For us and for our salvation he came down from heaven: by the power of the Holy Spirit he became incarnate from the Virgin Mary, and was made man.&nbsp; For our sake he was crucified under Pontius Pilate; he suffered death and was buried.&nbsp; On the third day he rose again in accordance with the Scriptures; he ascended into heaven and is seated at the right hand of the Father.&nbsp; He will come again in glory to judge the living and the dead, and his kingdom will have no end.</p><p>We believe in the Holy Spirit, the Lord, the giver of life, who proceeds from the Father and the Son. With the Father and the Son he is worshiped and glorified. He has spoken through the Prophets.&nbsp; We believe in one holy catholic and apostolic Church.&nbsp; We acknowledge one baptism for the forgiveness of sins.&nbsp; We look for the resurrection of the dead, and the life of the world to come. Amen.</p>',
                'created_at' => '2025-06-07 23:11:44',
                'updated_at' => '2025-06-07 23:11:44',
            ],
            2 => [
                'id' => 3,
                'title' => 'Romans 8:1-4a, 28-30, 38-39',
                'type' => 'assurance-of-pardon',
                'text' => '<h3>Leader</h3><p>There is therefore now no condemnation for those who are in Christ Jesus. For the law of the Spirit of life has set you free in Christ Jesus from the law of sin and death. For God has done what the law, weakened by the flesh, could not do. By sending his own Son in the likeness of sinful flesh and for sin, he condemned sin in the flesh, in order that the righteous requirement of the law might be fulfilled in us. And we know that for those who love God all things work together for good, for those who are called according to his purpose. For those whom he foreknew he also predestined to be conformed to the image of his Son, in order that he might be the firstborn among many brothers. And those whom he predestined he also called, and those whom he called he also justified, and those whom he justified he also glorified. I am sure that neither death nor life, nor angels nor rulers, nor things present nor things to come, nor powers, nor height nor depth, nor anything else in all creation, will be able to separate us from the love of God in Christ Jesus our Lord.</p>',
                'created_at' => '2025-06-07 23:12:52',
                'updated_at' => '2025-06-07 23:12:52',
            ],
            3 => [
                'id' => 4,
                'title' => '1 Corinthians 15:3-4',
                'type' => 'assurance-of-pardon',
                'text' => '<h3>Leader</h3><p>For I delivered to you as of first importance what I also received: that Christ died for our sins in accordance with the Scriptures, that he was buried, that he was raised on the third day in accordances with the Scriptures.</p>',
                'created_at' => '2025-06-07 23:13:35',
                'updated_at' => '2025-06-07 23:13:35',
            ],
            4 => [
                'id' => 5,
                'title' => '1 Thessalonians 5:23-24, 28',
                'type' => 'benediction',
                'text' => '<p>Now may the God of peace himself sanctify you completely, and may your whole spirit and soul and body be kept blameless at the coming of our Lord Jesus Christ. He who calls you is faithful; he will surely do it. The grace of our Lord Jesus Christ be with you.</p>',
                'created_at' => '2025-06-07 23:14:09',
                'updated_at' => '2025-06-07 23:14:09',
            ],
            5 => [
                'id' => 6,
                'title' => 'Psalm 136:4-6 (Call and Response)',
                'type' => 'call-to-worship',
                'text' => '<h3>Leader</h3><p>He alone does great wonders.</p><h3>Congregation</h3><p>His faithful love endures forever.</p><h3>Leader</h3><p>He made the heavens skillfully.</p><h3>Congregation</h3><p>His faithful love endures forever.</p><h3>Leader</h3><p>He spread the land on the waters.</p><h3>Congregation</h3><p>His faithful love endures forever.</p>',
                'created_at' => '2025-07-05 15:10:49',
                'updated_at' => '2025-07-05 18:17:36',
            ],
            6 => [
                'id' => 7,
                'title' => 'Matthew 5:20, 48; 6:1, 33; 7:12',
                'type' => 'law',
                'text' => '<h3>Leader</h3><p>For I say to you that unless your righteousness surpasses that of the scribes and Pharisees, you will not enter the kingdom of heaven. Therefore you are to be perfect, as your heavenly Father is perfect. Beware of practicing your righteousness before men to be noticed by them; otherwise you have no reward with your Father who is in heaven. But seek first His kingdom and His righteousness, and all these things will be added to you. In everything, therefore, treat people the same way you want them to treat you, for this is the Law and the Prophets. Amen.</p>',
                'created_at' => '2025-07-05 15:11:39',
                'updated_at' => '2025-07-05 18:25:33',
            ],
            7 => [
                'id' => 8,
                'title' => 'Gloria Patri',
                'type' => 'praise',
                'text' => '<h3>Congregation</h3><p>Glory to the Father, and to the Son, and to the Holy Spirit, As it was in the beginning, is now, and ever shall be world without end. Amen.</p>',
                'created_at' => '2025-07-05 15:16:13',
                'updated_at' => '2025-07-05 18:34:13',
            ],
            8 => [
                'id' => 9,
                'title' => 'Athanasian Creed (Part 1)',
                'type' => 'creed',
                'text' => '<h3>Congregation</h3><p>Whosoever will be saved, before all things it is necessary that he hold the catholic faith.&nbsp; Which faith except everyone do keep whole and undefiled, without doubt he shall perish everlastingly.&nbsp; And the catholic faith is this: That we worship one God in Trinity, and Trinity in Unity, neither confounding the persons, nor dividing the substance.</p><p>For there is one Person of the Father, another of the Son, and another of the Holy Spirit.&nbsp; But the godhead of the Father, of the Son, and of the Holy Spirit, is all one, the glory equal, the majesty co-eternal.</p><p>Such as the Father is, such is the Son, and such is the Holy Spirit. The Father uncreated, the Son uncreated, and the Holy Spirit uncreated.&nbsp; The Father incomprehensible, the Son incomprehensible, and the Holy Spirit incomprehensible.</p><p>The Father eternal, the Son eternal, and the Holy Spirit eternal.&nbsp; And yet they are not three eternals, but one Eternal.</p><p>As also there are not three incomprehensibles, nor three uncreated, but one Uncreated, and one Incomprehensible.&nbsp; So likewise the Father is Almighty, the Son Almighty, and the Holy Spirit Almighty.&nbsp; And yet they are not three almighties, but one Almighty.</p><p>So the Father is God, the Son is God, and the Holy Spirit is God.&nbsp; And yet they are not three gods, but one God.</p><p>So likewise the Father is Lord, the Son Lord, and the Holy Spirit Lord.&nbsp; And yet not three lords, but one Lord.</p>',
                'created_at' => '2025-07-05 16:10:12',
                'updated_at' => '2025-07-05 18:33:27',
            ],
            9 => [
                'id' => 10,
                'title' => 'Athanasian Creed (Part 2)',
                'type' => 'creed',
                'text' => '<h3>Congregation</h3><p>For as we are compelled by the Christian verity to acknowledge each Person by Himself to be both God and Lord, so we are also forbidden by the catholic religion to say that there are three gods or three lords.</p><p>The Father is made of none, neither created, nor begotten.&nbsp; The Son is of the Father alone, not made, nor created, but begotten.&nbsp; The Holy Spirit is of the Father, neither made, nor created, nor begotten, but proceeding.</p><p>So there is one Father, not three fathers; one Son, not three sons; one Holy Spirit, not three holy spirits.</p><p>And in the Trinity none is before or after another; none is greater or less than another, but all three Persons are co-eternal together and co-equal. So that in all things, as is aforesaid, the Unity in Trinity and the Trinity in Unity is to be worshipped.</p><p>He therefore that will be saved must think thus of the Trinity.</p><p>Furthermore, it is necessary to everlasting salvation that he also believe rightly the Incarnation of our Lord Jesus Christ.&nbsp; For the right faith is, that we believe and confess, that our Lord Jesus Christ, the Son of God, is God and man; God, of the substance of the Father, begotten before the worlds; and man of the substance of his mother, born in the world; perfect God and perfect man, of a rational soul and human flesh subsisting. Equal to the Father, as touching His godhead; and inferior to the Father, as touching His manhood; who, although He is God and man, yet he is not two, but one Christ; one, not by conversion of the godhead into flesh but by taking of the manhood into God; one altogether; not by confusion of substance, but by unity of person.&nbsp; For as the rational soul and flesh is one man, so God and man is one Christ; who suffered for our salvation, descended into hell, rose again the third day from the dead.&nbsp; He ascended into heaven, He sits at the right hand of the Father, God Almighty, from whence He will come to judge the quick and the dead.&nbsp; At His coming all men will rise again with their bodies and shall give account for their own works.&nbsp; And they that have done good shall go into life everlasting; and they that have done evil into everlasting fire.</p><p>This is the catholic faith, which except a man believe faithfully, he cannot be saved.</p>',
                'created_at' => '2025-07-05 16:12:55',
                'updated_at' => '2025-07-05 18:33:39',
            ],
            10 => [
                'id' => 11,
                'title' => 'Ephesians 1:3-10',
                'type' => 'assurance-of-pardon',
                'text' => '<h3>Leader</h3><p>Blessed be the God and Father of our Lord Jesus Christ, who has blessed us in Christ with every spiritual blessing in the heavenly places, even as he chose us in him before the foundation of the world, that we should be holy and blameless before him. In love he predestined us for adoption to himself as sons through Jesus Christ, according to the purpose of his will, to the praise of his glorious grace, with which he has blessed us in the Beloved. In him we have redemption through his blood, the forgiveness of our trespasses, according to the riches of his grace, which he lavished upon us, in all wisdom and insight making known to us the mystery of his will, according to his purpose, which he set forth in Christ as a plan for the fullness of time, to unite all things in him, things in heaven and things on earth.</p>',
                'created_at' => '2025-07-05 16:15:59',
                'updated_at' => '2025-07-05 18:30:34',
            ],
            11 => [
                'id' => 12,
                'title' => 'Revelation 22:20-21',
                'type' => 'benediction',
                'text' => '<h3>Leader</h3><p>He who testifies to these things says, “Surely I am coming soon.” Amen. Come, Lord Jesus! The grace of the Lord Jesus be with all.</p><h3>Congregation</h3><p>Amen.</p>',
                'created_at' => '2025-07-05 16:17:46',
                'updated_at' => '2025-07-05 18:34:44',
            ],
            12 => [
                'id' => 13,
                'title' => 'Almighty God, unto whom all hearts are open',
                'type' => 'confession-of-sin',
                'text' => '<h3>Congregation</h3><p>Almighty God, unto whom all hearts are open, all desires known, and from whom no secrets are hidden, cleanse the thoughts of our hearts by the inspiration of your Holy Spirit, so that we may perfectly love you, and worthily magnify your holy name; through Christ our Lord. Amen.</p>',
                'created_at' => '2025-07-05 16:27:13',
                'updated_at' => '2025-07-05 18:30:19',
            ],
            13 => [
                'id' => 14,
                'title' => 'Be Thou My Vision (Day 9)',
                'type' => 'prayer',
                'text' => '<h3>Leader</h3><p>Great are you, O Lord, and greatly to be praised; great is your power, and of your wisdom there is no end. And man, being a part of your creation, desires to praise you—man, who bears about with him his mortality, the witness of his sin, even the witness that you resist the proud—yet man, this part of your creation, desires to praise you. You move us to delight in praising you; for you have made us for yourself, and our hearts are restless until they rest in you.</p><p>Almighty Lord, our God, whose eyes are in every place beholding the evil and the good, and who sees not only our outward actions, but all our most secret thoughts—we pray you to maintain in us this day a constant sense of your presence, and to preserve us from sinning against you. We are exposed to dangers by night and by day; our lives are in your hands, and unto you do we look for preservation from every evil.</p><p>O Lord, teach us to be ever mindful of you. When we go out and come in, and when we are alone and in company, may we bear in mind that you are continually with us, and that you take account of all we think, and speak, and do.</p><p>As we open your Word, Blessed Lord, we know that you have caused all Holy Scriptures to be written for our learning. Grant us that we may in such a way hear them, read, mark, learn, and inwardly digest them; that by patience and comfort of your holy Word, we may embrace and ever hold fast the blessed hope of everlasting life, which you have given us in our Savior Jesus Christ. Amen.</p>',
                'created_at' => '2025-07-05 17:00:47',
                'updated_at' => '2025-07-05 18:33:55',
            ],
            14 => [
                'id' => 15,
                'title' => 'Psalm 136:7-9',
                'type' => 'call-to-worship',
                'text' => '<h3>Leader</h3><p>He made the great lights</p><h3>Congregation</h3><p>His faithful love endures forever. </p><h3>Leader</h3><p>The sun to rule by day, </p><h3>Congregation</h3><p>His faithful love endures forever. </p><h3>Leader </h3><p>The moon and stars to rule by night. </p><h3>Congregation</h3><p>His faithful love endures forever.</p>',
                'created_at' => '2025-07-12 02:04:20',
                'updated_at' => '2025-07-12 02:04:20',
            ],
            15 => [
                'id' => 16,
                'title' => '2 Peter 1:2-3',
                'type' => 'benediction',
                'text' => '<h3>Leader</h3><p>May grace and peace be multiplied to you in the knowledge of God and of Jesus our Lord. His divine power has granted to us all things that pertain to life and godliness, through the knowledge of him who called us to his own glory and excellence.</p><h3>Congregation</h3><p>Amen</p>',
                'created_at' => '2025-07-12 02:05:30',
                'updated_at' => '2025-07-12 02:05:30',
            ],
            16 => [
                'id' => 17,
                'title' => 'Matthew 5:3-10',
                'type' => 'law',
                'text' => '<h3>Leader</h3><p>Blessed are the poor in spirit, for theirs is the kingdom of heaven. Blessed are those who mourn, for they shall be comforted. Blessed are the meek, for they shall inherit the earth. Blessed are those who hunger and thirst for righteousness, for they shall be satisfied. Blessed are the merciful, for they shall receive mercy. Blessed are the pure in heart, for they shall see God. Blessed are the peacemakers, for they shall be called sons of God. Blessed are those who are persecuted for righteousness’ sake, for theirs is the kingdom of heaven.</p>',
                'created_at' => '2025-07-12 02:06:46',
                'updated_at' => '2025-07-12 02:08:16',
            ],
            17 => [
                'id' => 18,
                'title' => 'Ashamed and Blush to Lift My Face',
                'type' => 'confession-of-sin',
                'text' => '<h3>Congregation</h3><p>O God, I am ashamed and blush to lift my face to you, for our iniquities have risen higher than our heads, and our guilt has mounted up to the heavens. And now, O God, what shall we say after this? For we have forsaken your commandments. Amen.</p>',
                'created_at' => '2025-07-12 02:07:36',
                'updated_at' => '2025-07-12 02:07:36',
            ],
            18 => [
                'id' => 19,
                'title' => 'Romans 7:21 - 8:4',
                'type' => 'assurance-of-pardon',
                'text' => '<h3>Leader</h3><p>So I find it to be a law that when I want to do right, evil lies close at hand. For I delight in the law of God, in my inner being, but I see in my members another law waging war against the law of my mind and making me captive to the law of sin that dwells in my members. Wretched man that I am! Who will deliver me from this body of death? Thanks be to God through Jesus Christ our Lord! So then, I myself serve the law of God with my mind, but with my flesh I serve the law of sin. There is therefore now no condemnation for those who are in Christ Jesus. For the law of the Spirit of life has set you free in Christ Jesus from the law of sin and death. For God has done what the law, weakened by the flesh, could not do. By sending his own Son in the likeness of sinful flesh and for sin, he condemned sin in the flesh, in order that the righteous requirement of the law might be fulfilled in us, who walk not according to the flesh but according to the Spirit.</p>',
                'created_at' => '2025-07-12 02:09:53',
                'updated_at' => '2025-07-12 02:15:18',
            ],
            19 => [
                'id' => 20,
                'title' => 'Be Thou My Vision (Day 13)',
                'type' => 'prayer',
                'text' => '<p>We praise and glorify you our Lord and owner, for we and all things are your own. We praise and glorify you our king and ruler, for we are your subjects, and our perfect obedience is your due. Just are all your laws and judgment; true and sure is all your Word. We praise and glorify you, our great benefactor. In you we live, and move, and are: all that we are, or have, or can do, is wholly from you, the cause of all, and all is for you, for you are our end. Delightfully to love you is our greatest duty, and our only felicity, for you are love itself, and infinitely amiable.</p><p>Grant, Almighty God, that as you shine on us by your Word, we may not be blind at midday, nor willfully seek darkness, and thus lull our minds asleep; but may we be roused daily by your words, and may we stir up ourselves more and more to fear your name and thus present ourselves and all our pursuits as a sacrifice to you, that you may peaceably rule, and perpetually dwell in us, until you gather us to your celestial habitation, where there is reserved for us eternal rest and glory, through Jesus Christ our Lord.</p><p>Assist us mercifully, O Lord, in these our supplications and prayers, and dispose the way of your servants toward the attainment of everlasting salvation—that among all the changes and chances of this mortal life, they may ever be defended by your most gracious and ready help; through Christ our Lord. Amen.</p>',
                'created_at' => '2025-07-12 14:34:52',
                'updated_at' => '2025-07-12 14:34:52',
            ],
            20 => [
                'id' => 21,
                'title' => 'Psalm 136:10-15',
                'type' => 'call-to-worship',
                'text' => '<h3>Leader</h3><p>He struck the firstborn of the Egyptians </p><h3>Congregation</h3><p>His faithful love endures forever. </p><h3>Leader</h3><p>and brought Israel out from among them </p><h3>Congregation</h3><p>His faithful love endures forever. </p><h3>Leader</h3><p>with a strong hand and outstretched arm </p><h3>Congregation</h3><p>His faithful love endures forever.</p><h3>Leader</h3><p>He divided the Red Sea </p><h3>Congregation</h3><p>His faithful love endures forever. </p><h3>Leader</h3><p>and led Israel through,</p><h3>Congregation</h3><p>His faithful love endures forever. </p><h3>Leader</h3><p>but hurled Pharaoh and his army into the Red Sea </p><h3>Congregation</h3><p>His faithful love endures forever.</p>',
                'created_at' => '2025-07-19 13:13:08',
                'updated_at' => '2025-07-19 13:13:08',
            ],
            21 => [
                'id' => 22,
                'title' => 'Deuteronomy 30:15-20',
                'type' => 'law',
                'text' => '<h3>Leader</h3><p>See, I have set before you today life and good, death and evil. If you obey the commandments of the LORD your God that I command you today, by loving the LORD your God, by walking in his ways, and by keeping his commandments and his statutes and his rules, then you shall live and multiply, and the LORD your God will bless you in the land that you are entering to take possession of it. But if your heart turns away, and you will not hear, but are drawn away to worship other gods and serve them, I declare to you today, that you shall surely perish. You shall not live long in the land that you are going over the Jordan to enter and possess. I call heaven and earth to witness against you today, that I have set before you life and death, blessing and curse. Therefore choose life, that you and your offspring may live, loving the LORD your God, obeying his voice and holding fast to him, for he is your life and length of days, that you may dwell in the land that the LORD swore to your fathers, to Abraham, to Isaac, and to Jacob, to give them.</p>',
                'created_at' => '2025-07-19 19:50:24',
                'updated_at' => '2025-07-19 19:50:24',
            ],
            22 => [
                'id' => 23,
                'title' => 'Almighty, eternal God.',
                'type' => 'confession-of-sin',
                'text' => '<h3>Congregation</h3><p>Almighty, eternal God. Forgive us our sin and lead us to eternal life, through Jesus Christ our Lord. Amen.</p>',
                'created_at' => '2025-07-19 19:51:11',
                'updated_at' => '2025-07-19 19:51:11',
            ],
            23 => [
                'id' => 24,
                'title' => 'Romans 3:21-26',
                'type' => 'assurance-of-pardon',
                'text' => '<h3>Leader</h3><p>But now the righteousness of God has been manifested apart from the law, although the Law and the Prophets bear witness to it⁠— the righteousness of God through faith in Jesus Christ for all who believe. For there is no distinction: for all have sinned and fall short of the glory of God, and are justified by his grace as a gift, through the redemption that is in Christ Jesus, whom God put forward as a propitiation by his blood, to be received by faith. This was to show God’s righteousness, because in his divine forbearance he had passed over former sins. It was to show his righteousness at the present time, so that he might be just and the justifier of the one who has faith in Jesus.</p>',
                'created_at' => '2025-07-19 19:52:32',
                'updated_at' => '2025-07-19 19:52:32',
            ],
            24 => [
                'id' => 25,
                'title' => 'Ligonier Statement on Christology',
                'type' => 'creed',
                'text' => '<p>We confess the mystery and wonder of God made flesh and rejoice in our great salvation through Jesus Christ our Lord.</p><p>With the Father and the Holy Spirit, the Son created all things, sustains all things, and makes all things new. Truly God, He became truly man, two natures in one person.</p><p>He was born of the Virgin Mary and lived among us. Crucified, dead, and buried, He rose on the third day, ascended to heaven, and will come again in glory and judgment.</p><p>For us, He kept the Law, atoned for sin, and satisfied God’s wrath. He took our filthy rags and gave us His righteous robe.</p><p>He is our Prophet, Priest, and King, building His church, interceding for us, and reigning over all things.</p><p>Jesus Christ is Lord; we praise His holy Name forever. Amen.</p>',
                'created_at' => '2025-07-19 19:57:07',
                'updated_at' => '2025-07-19 19:57:07',
            ],
            25 => [
                'id' => 27,
                'title' => 'O Most High, Creator of the ends of the earth',
                'type' => 'prayer',
                'text' => '<p>O Most High, Creator of the ends of the earth, Governor of the universe, Judge of all men, Head of the church, Saviour of sinners; your greatness is unsearchable, your goodness infinite, your compassions unfailing, your providence boundless, your mercies ever new. We bless your for the words of salvation. How important, suitable, encouraging are the doctrines, promises, and invitations of the gospel of peace!</p><p>We are lost: but in it you have presented to us a full, free and eternal salvation; weak: but here we learn that help is found in One that is mighty, poor: but in him we discover unsearchable riches, blind: but we find he has treasures of wisdom and knowledge. We thank you for your unspeakable gift.</p><p>Your Son is our only refuge, foundation, hope, confidence; We depend upon his death, rest in his righteousness, desire to bear his image; May his glory fill our minds, his love reign in our affections, his words impress on our hearts his example inspire our obedience his cross inflame us with zeal. Amen.</p>',
                'created_at' => '2025-07-19 22:36:58',
                'updated_at' => '2025-07-19 22:36:58',
            ],
            26 => [
                'id' => 28,
                'title' => 'Deuteronomy 6:4-9',
                'type' => 'law',
                'text' => '<h3>Leader</h3><p>Hear, O Israel: The LORD our God, the LORD is one. You shall love the LORD your God with all your heart and with all your soul and with all your might. And these words that I command you today shall be on your heart. You shall teach them diligently to your children, and shall talk of them when you sit in your house, and when you walk by the way, and when you lie down, and when you rise. You shall bind them as a sign on your hand, and they shall be as frontlets between your eyes. You shall write them on the doorposts of your house and on your gates.</p>',
                'created_at' => '2025-07-26 18:19:50',
                'updated_at' => '2025-07-26 18:19:50',
            ],
            27 => [
                'id' => 29,
                'title' => 'Most Merciful God, we confess',
                'type' => 'confession-of-sin',
                'text' => '<h3>Congregation</h3><p>Most merciful God, we confess that we have sinned against you in thought, word, and deed, by what we have done, and by what we have left undone. We have not loved you with our whole heart; we have not loved our neighbors as ourselves. We are truly sorry and we humbly repent. For the sake of your Son Jesus Christ, have mercy on us and forgive us; that we may delight in your will, and walk in your ways, to the glory of your Name. Amen.</p>',
                'created_at' => '2025-07-26 18:20:45',
                'updated_at' => '2025-07-26 18:20:45',
            ],
            28 => [
                'id' => 30,
                'title' => 'Titus 3:4-7',
                'type' => 'assurance-of-pardon',
                'text' => '<h3>Leader</h3><p>But when the goodness and loving kindness of God our Savior appeared, he saved us, not because of works done by us in righteousness, but according to his own mercy, by the washing of regeneration and renewal of the Holy Spirit, whom he poured out on us richly through Jesus Christ our Savior, so that being justified by his grace we might become heirs according to the hope of eternal life.</p>',
                'created_at' => '2025-07-26 18:21:25',
                'updated_at' => '2025-07-26 18:21:25',
            ],
            29 => [
                'id' => 31,
                'title' => 'The 1689: Of Holy Scripture (1.1-5)',
                'type' => 'confession',
                'text' => '<h3>Leader</h3><p>The Holy Scripture is the only sufficient, certain, and infallible rule of all saving knowledge, faith, and obedience, although the light of nature, and the works of creation and providence do so far manifest the goodness, wisdom, and power of God, as to leave men inexcusable; yet they are not sufficient to give that knowledge of God and His will which is necessary unto salvation. Therefore it pleased the Lord at sundry times and in diversified manners to reveal Himself, and to declare His will unto His church; and afterward for the better preserving and propagating of the truth, and for the more sure establishment and comfort of the church against the corruption of the flesh, and the malice of Satan, and of the world, to commit the same wholly unto writing; which makes the Holy Scriptures to be most necessary, those former ways of God’s revealing His will unto His people being now completed.</p><p>Under the name of Holy Scripture, or the Word of God written, are now contained all the books of the Old and New Testaments, which are these: Genesis, Exodus, Leviticus, Numbers, Deuteronomy, Joshua, Judges, Ruth, 1 Samuel, 2 Samuel, 1 Kings, 2 Kings, 1 Chronicles, 2 Chronicles, Ezra, Nehemiah, Esther, Job, Psalms, Proverbs, Ecclesiastes, The Song of Solomon, Isaiah, Jeremiah, Lamentations, Ezekiel, Daniel, Hosea, Joel, Amos, Obadiah, Jonah, Micah, Nahum, Habakkuk, Zephaniah, Haggai, Zechariah, Malachi, Matthew, Mark, Luke, John, Acts, Romans, 1 Corinthians, 2 Corinthians, Galatians, Ephesians, Philippians, Colossians, 1 Thessalonians, 2 Thessalonians, 1 Timothy, 2 Timothy, Titus, Philemon, Hebrews, James, 1 Peter, 2 Peter, 1 John, 2 John, 3 John, Jude, Revelation.</p><p>All of which are given by the inspiration of God, to be the rule of faith and life.</p><p>The books commonly called Apocrypha, not being of divine inspiration, are no part of the canon or rule of the Scripture, and, therefore, are of no authority to the church of God, nor to be any otherwise approved or made use of than other human writings.</p><p>The authority of the Holy Scripture, for which it ought to be believed, depends not upon the testimony of any man or church, but wholly upon God (who is truth itself), the author thereof; therefore it is to be received because it is the Word of God.</p>',
                'created_at' => '2025-07-26 18:30:56',
                'updated_at' => '2025-07-26 18:31:14',
            ],
            30 => [
                'id' => 32,
                'title' => 'The 1689: Of Holy Scripture (1.6-8)',
                'type' => 'confession',
                'text' => '<h3>Leader</h3><p>We may be moved and induced by the testimony of the church of God to a high and reverent esteem of the Holy Scriptures; and the heavenliness of the matter, the efficacy of the doctrine, and the majesty of the style, the consent of all the parts, the scope of the whole (which is to give all glory to God), the full discovery it makes of the only way of man’s salvation, and many other incomparable excellencies, and entire perfections thereof, are arguments whereby it does abundantly evidence itself to be the Word of God; yet notwithstanding, our full persuasion and assurance of the infallible truth, and divine authority thereof, is from the inward work of the Holy Spirit bearing witness by and with the Word in our hearts.</p><p>The whole counsel of God concerning all things necessary for His own glory, man’s salvation, faith and life, is either expressly set down or necessarily contained in the Holy Scripture: unto which nothing at any time is to be added, whether by new revelation of the Spirit, or traditions of men. Nevertheless, we acknowledge the inward illumination of the Spirit of God to be necessary for the saving understanding of such things as are revealed in the Word, and that there are some circumstances concerning the worship of God, and government of the church, common to human actions and societies, which are to be ordered by the light of nature and Christian prudence, according to the general rules of the Word, which are always to be observed.</p><p>All things in Scripture are not alike plain in themselves, nor alike clear unto all; yet those things which are necessary to be known, believed and observed for salvation, are so clearly propounded and opened in some place of Scripture or other, that not only the learned, but the unlearned, in a due use of ordinary means, may attain to a sufficient understanding of them.</p>',
                'created_at' => '2025-07-26 18:32:12',
                'updated_at' => '2025-07-26 18:32:12',
            ],
            31 => [
                'id' => 33,
                'title' => 'The 1689: Of Holy Scripture (1.9-11)',
                'type' => 'confession',
                'text' => '<h3>Leader</h3><p>We may be moved and induced by the testimony of the church of God to a high and reverent esteem of the Holy Scriptures; and the heavenliness of the matter, the efficacy of the doctrine, and the majesty of the style, the consent of all the parts, the scope of the whole (which is to give all glory to God), the full discovery it makes of the only way of man’s salvation, and many other incomparable excellencies, and entire perfections thereof, are arguments whereby it does abundantly evidence itself to be the Word of God; yet notwithstanding, our full persuasion and assurance of the infallible truth, and divine authority thereof, is from the inward work of the Holy Spirit bearing witness by and with the Word in our hearts.</p><p>The whole counsel of God concerning all things necessary for His own glory, man’s salvation, faith and life, is either expressly set down or necessarily contained in the Holy Scripture: unto which nothing at any time is to be added, whether by new revelation of the Spirit, or traditions of men. Nevertheless, we acknowledge the inward illumination of the Spirit of God to be necessary for the saving understanding of such things as are revealed in the Word, and that there are some circumstances concerning the worship of God, and government of the church, common to human actions and societies, which are to be ordered by the light of nature and Christian prudence, according to the general rules of the Word, which are always to be observed.</p><p>All things in Scripture are not alike plain in themselves, nor alike clear unto all; yet those things which are necessary to be known, believed and observed for salvation, are so clearly propounded and opened in some place of Scripture or other, that not only the learned, but the unlearned, in a due use of ordinary means, may attain to a sufficient understanding of them.</p>',
                'created_at' => '2025-07-26 18:33:07',
                'updated_at' => '2025-07-26 18:33:07',
            ],
            32 => [
                'id' => 34,
                'title' => 'The 1689: Of God and the Holy Trinity (2.1-3)',
                'type' => 'confession',
                'text' => '<h3>Leader</h3><p>The Lord our God is but one only living and true God; whose subsistence is in and of Himself, infinite in being and perfection; whose essence cannot be comprehended by any but Himself; a most pure spirit, invisible, without body, parts, or passions, who only hath immortality, dwelling in the light which no man can approach unto; who is immutable, immense, eternal, incomprehensible, almighty, every way infinite, most holy, most wise, most free, most absolute; working all things according to the counsel of His own immutable and most righteous will, for His own glory; most loving, gracious, merciful, long-suffering, abundant in goodness and truth, forgiving iniquity, transgression, and sin; the rewarder of them that diligently seek Him, and withal most just and terrible in His judgments, hating all sin, and who will by no means clear the guilty.</p><p>God, having all life, glory, goodness, blessedness, in and of Himself, is alone in and unto Himself all-sufficient, not standing in need of any creature which He hath made, nor deriving any glory from them, but only manifesting His own glory in, by, unto, and upon them; He is the alone fountain of all being, of whom, through whom, and to whom are all things, and He hath most sovereign dominion over all creatures, to do by them, for them, or upon them, whatsoever Himself pleases; in His sight all things are open and manifest, His knowledge is infinite, infallible, and independent upon the creature, so as nothing is to Him contingent or uncertain; He is most holy in all His counsels, in all His works, and in all His commands; to Him is due from angels and men, whatsoever worship, service, or obedience, as creatures they owe unto the Creator, and whatever He is further pleased to require of them.</p><p>In this divine and infinite Being there are three subsistences, the Father, the Word or Son, and Holy Spirit, of one substance, power, and eternity, each having the whole divine essence, yet the essence undivided: the Father is of none, neither begotten nor proceeding; the Son is eternally begotten of the Father; the Holy Spirit proceeding from the Father and the Son; all infinite, without beginning, therefore but one God, who is not to be divided in nature and being, but distinguished by several peculiar relative properties and personal relations; which doctrine of the Trinity is the foundation of all our communion with God, and comfortable dependence on Him.</p>',
                'created_at' => '2025-07-26 18:35:59',
                'updated_at' => '2025-07-26 18:35:59',
            ],
            33 => [
                'id' => 35,
                'title' => 'From the Book of Common Prayer',
                'type' => 'prayer',
                'text' => '<h3>Leader</h3><p>Almighty God, who pours out on all who desire it the spirit of grace and of supplication. Deliver us when we draw near to you, from coldness of heart and wanderings of mind, that with steadfast thoughts and kindled affections, we may worship in spirit and in truth.</p><p>You have promised to hear the petitions of those who ask in your Son’s name. We beseech you to mercifully incline your ear to us and grant that those things which we have faithfully asked according to your will may effectually be obtained to the setting forth of your glory.</p><p>Grant that the words which we hear this day with our outward ears may through your grace be so grafted inwardly in our hearts that they may bring forth in us the fruit of the Spirit to the honor and praise of your name.</p><p>O God our King, by the resurrection of your Son Jesus Christ on the first day of the week, you conquered sin, put death to flight, and gave us the hope of everlasting life: Redeem all our days by this victory; forgive our sins, banish our fears, make us bold to praise you and to do your will; and steel us to wait for the consummation of your kingdom on the last great Day; through the same Jesus Christ our Lord. Amen.</p>',
                'created_at' => '2025-07-26 18:37:40',
                'updated_at' => '2025-07-26 18:37:40',
            ],
            34 => [
                'id' => 36,
                'title' => 'Psalm 136:23-26',
                'type' => 'call-to-worship',
                'text' => '<h3>Leader</h3><p>He remembered us in our humiliation</p><h3>Congregation</h3><p>His faithful love endures forever.</p><h3>Leader</h3><p><strong><sup>&nbsp;</sup></strong>and rescued us from our foes.</p><h3>Congregation</h3><p>His faithful love endures forever.</p><h3>Leader</h3><p>He gives food to every creature.</p><h3>Congregation</h3><p>His faithful love endures forever.</p><h3>Leader</h3><p>Give thanks to the God of heaven!</p><h3>Congregation</h3><p>His faithful love endures forever.</p>',
                'created_at' => '2025-07-26 19:11:49',
                'updated_at' => '2025-07-26 19:11:49',
            ],
            35 => [
                'id' => 37,
                'title' => 'Romans 16:20',
                'type' => 'benediction',
                'text' => '<h3>Leader</h3><p>The God of peace will soon crush Satan under your feet. The grace of our Lord Jesus Christ be with you.</p><h3>Congregation</h3><p>Amen</p>',
                'created_at' => '2025-07-26 19:12:52',
                'updated_at' => '2025-07-26 19:12:52',
            ],
            36 => [
                'id' => 38,
                'title' => 'An Orthodox Catechism - Lord\'s Day 1: Comfort in Life and Death (Question 1)',
                'type' => 'catechism',
                'text' => '<h3>Leader</h3><p>What is your only comfort in life and death?</p><h3>Congregation</h3><p>That both in soul and body, whether I live or die, I am not my own, but belong wholly to my most faithful Lord and Savior Jesus Christ—who by his most precious blood fully satisfying for my sins, has delivered me from all the power of the devil, and so preserves me, that without the will of my heavenly Father not so much as a hair may fall from my head. Yes, all things must serve for my safety—therefore by his Spirit, he also assures me of everlasting life, and makes me ready and prepared, that henceforth I may live to him.</p>',
                'created_at' => '2025-07-27 01:18:58',
                'updated_at' => '2025-08-02 19:52:37',
            ],
            37 => [
                'id' => 39,
                'title' => 'Micah 6:6-8',
                'type' => 'call-to-worship',
                'text' => '<h3>Leader</h3><p>What should I bring before the LORD when I come to bow before God on high? Should I come before him with burnt offerings, with year-old calves? </p><p>Would the LORD be pleased with thousands of rams or with ten thousand streams of oil? Should I give my firstborn for my transgression, the offspring of my body for my own sin?</p><p>Mankind, he has told each of you what is good and what it is the LORD requires of you: to act justly, to love faithfulness, and to walk humbly with your God.</p>',
                'created_at' => '2025-08-02 13:48:22',
                'updated_at' => '2025-08-02 13:48:22',
            ],
            38 => [
                'id' => 40,
                'title' => 'Revelation 1:4b-6',
                'type' => 'benediction',
                'text' => '<h3>Leader</h3><p>Grace to you and peace from him who is and who was and who is to come, and from the seven spirits who are before his throne, and from Jesus Christ, the faithful witness, the firstborn of the dead, and the ruler of the kings of the earth. To him who loves us and freed us from our sins by his blood, and made us to be a kingdom, priests serving his God and Father, to him be glory and dominion forever and ever. </p><h3>Congregation</h3><p>Amen.</p>',
                'created_at' => '2025-08-02 13:50:22',
                'updated_at' => '2025-08-02 20:04:39',
            ],
            39 => [
                'id' => 41,
                'title' => '1 John 4:7-12',
                'type' => 'law',
                'text' => '<h3>Leader</h3><p>Beloved, let us love one another, for love is from God, and whoever loves has been born of God and knows God. Anyone who does not love does not know God, because God is love. In this the love of God was made manifest among us, that God sent his only Son into the world, so that we might live through him. In this is love, not that we have loved God but that he loved us and sent his Son to be the propitiation for our sins. Beloved, if God so loved us, we also ought to love one another. No one has ever seen God; if we love one another, God abides in us and his love is perfected in us.</p>',
                'created_at' => '2025-08-02 13:54:55',
                'updated_at' => '2025-08-02 13:54:55',
            ],
            40 => [
                'id' => 42,
                'title' => 'Our Lord and our God',
                'type' => 'confession-of-sin',
                'text' => '<h3>Congregation</h3><p>Our Lord and our God, we have fallen incredibly short of your glory. Be merciful to our unrighteousness. We embrace and rest in Christ alone for cleansing. Amen.</p>',
                'created_at' => '2025-08-02 13:55:36',
                'updated_at' => '2025-08-02 13:55:36',
            ],
            41 => [
                'id' => 43,
                'title' => 'Isaiah 55:1,3; John 6:35,37; John 7:37; Matthew 11:28-30',
                'type' => 'assurance-of-pardon',
                'text' => '<h3>Leader</h3><p>Come, everyone who thirsts, come to the waters; and he who has no money, come, buy and eat! Come, buy wine and milk without money and without price…Incline your ear, and come to me; hear, that your soul may live; and I will make with you an everlasting covenant, my steadfast, sure love for David.</p><p>Jesus said to them, “I am the bread of life; whoever comes to me shall not hunger, and whoever believes in me shall never thirst…All that the Father gives me will come to me, and whoever comes to me I will never cast out.”</p><p>On the last day of the feast, the great day, Jesus stood up and cried out, “If anyone thirsts, let him come to me and drink.”</p><p>Come to me, all who labor and are heavy laden, and I will give you rest. Take my yoke upon you, and learn from me, for I am gentle and lowly in heart, and you will find rest for your souls. For my yoke is easy, and my burden is light.</p>',
                'created_at' => '2025-08-02 13:58:30',
                'updated_at' => '2025-08-02 13:58:48',
            ],
            42 => [
                'id' => 44,
                'title' => 'An Orthodox Catechism - Lord\'s Day 2: Sin and Misery (Questions 2-3)',
                'type' => 'catechism',
                'text' => '<h3>Leader</h3><p>How many things are necessary for you to know that you, enjoying this comfort, may live and die happily?</p><h3>Congregation</h3><p>Three. The first: what is the greatness of my sin and misery. The second: how am I delivered from all sin and misery. The third: what thanks I owe to God for this delivery.</p><h3>Leader</h3><p>From where do you know your misery?</p><h3>Congregation</h3><p>Out of the Law of God.</p>',
                'created_at' => '2025-08-02 19:51:49',
                'updated_at' => '2025-08-02 19:51:49',
            ],
            43 => [
                'id' => 45,
                'title' => 'Be Thou My Vision (Day 6)',
                'type' => 'prayer',
                'text' => '<p>O Lord God, Father of mercies, the fountain of comfort and blessing, of life and peace, of plenty and pardon, who fills heaven with your glory, and earth with your goodness—We give you the most earnest, the most humble, and most enlarged returns of our glad and thankful hearts, for you have refreshed us with your comforts, and enlarged us with your blessing. You have made our flesh and bones to rejoice, for, besides the blessings of all mankind, the blessings of nature, and the blessings of grace, the support of every minute, and the comforts of every day, you have opened your bosom, and at this time have poured out an excellent expression of your loving kindness.</p><p>Grant, Almighty God, that as you shine on us by your Word, we may not be blind at midday, nor willfully seek darkness, and thus lull our minds asleep; but may we be roused daily by your words, and may we stir up ourselves more and more to fear your name and thus present ourselves and all our pursuits as a sacrifice to you, that you may peaceably rule, and perpetually dwell in us, until you gather us to your celestial habitation, where there is reserved for us eternal rest and glory, through Jesus Christ our Lord. Amen.</p>',
                'created_at' => '2025-08-02 19:57:22',
                'updated_at' => '2025-08-02 19:57:22',
            ],
            44 => [
                'id' => 46,
                'title' => 'Exodus 20:1-17',
                'type' => 'law',
                'text' => '<h3>Leader</h3><p>And God spoke all these words, saying, “I am the LORD your God, who brought you out of the land of Egypt, out of the house of slavery. You shall have no other gods before me. You shall not make for yourself a carved image, or any likeness of anything that is in heaven above, or that is in the earth beneath, or that is in the water under the earth. You shall not bow down to them or serve them, for I the LORD your God am a jealous God, visiting the iniquity of the fathers on the children to the third and the fourth generation of those who hate me, but showing steadfast love to thousands of those who love me and keep my commandments. You shall not take the name of the LORD your God in vain. Remember the Sabbath day, to keep it holy. Six days you shall labor, and do all your work, but the seventh day is a Sabbath to the LORD your God. Honor your father and your mother, that your days may be long in the land that the LORD your God is giving you. You shall not murder. You shall not commit adultery. You shall not steal. You shall not bear false witness against your neighbor. You shall not covet your neighbor’s house; you shall not covet your neighbor’s wife, or his male servant, or his female servant, or his ox, or his donkey, or anything that is your neighbor’s.”</p>',
                'created_at' => '2025-08-09 17:46:26',
                'updated_at' => '2025-08-09 17:46:26',
            ],
            45 => [
                'id' => 47,
                'title' => 'Jeremiah 3:25 - Let us Lie Down in our Shame',
                'type' => 'confession-of-sin',
                'text' => '<h3>Congregation</h3><p>Let us lie down in our shame, and let our dishonor cover us. For we have sinned against the LORD our God, we and our fathers, from our youth even to this day, and we have not obeyed the voice of the LORD our God.</p>',
                'created_at' => '2025-08-09 17:48:10',
                'updated_at' => '2025-08-09 17:49:02',
            ],
            46 => [
                'id' => 48,
                'title' => 'Isaiah 43:1-4',
                'type' => 'assurance-of-pardon',
                'text' => '<h3>Leader</h3><p>But now thus says the LORD, he who created you, O Jacob, he who formed you, O Israel: “Fear not, for I have redeemed you; I have called you by name, you are mine. When you pass through the waters, I will be with you; and through the rivers, they shall not overwhelm you; when you walk through fire you shall not be burned, and the flame shall not consume you. For I am the LORD your God, the Holy One of Israel, your Savior. I give Egypt as your ransom, Cush and Seba in exchange for you. Because you are precious in my eyes, and honored, and I love you, I give men in return for you, peoples in exchange for your life.</p>',
                'created_at' => '2025-08-09 17:48:46',
                'updated_at' => '2025-08-09 17:48:46',
            ],
            47 => [
                'id' => 49,
                'title' => 'Deuteronomy 7:6-9',
                'type' => 'call-to-worship',
                'text' => '<h3>Leader</h3><p>For you are a holy people belonging to the LORD your God. The LORD your God has chosen you to be his own possession out of all the peoples on the face of the earth. “The LORD had his heart set on you and chose you, not because you were more numerous than all peoples, for you were the fewest of all peoples. But because the LORD loved you and kept the oath he swore to your ancestors, he brought you out with a strong hand and redeemed you from the place of slavery, from the power of Pharaoh king of Egypt. Know that the LORD your God is God, the faithful God who keeps his gracious covenant loyalty for a thousand generations with those who love him and keep his commands.</p>',
                'created_at' => '2025-08-09 17:49:47',
                'updated_at' => '2025-08-09 17:49:47',
            ],
            48 => [
                'id' => 50,
                'title' => 'An Orthodox Catechism - Lord\'s Day 3: Law and Ability (Questions 4-5)',
                'type' => 'catechism',
                'text' => '<h3>Leader</h3><p>What does the Law of God require of us?</p><h3>Congregation</h3><p>That which Christ does summarily teach us, “You shall love the Lord your God with all your heart, and with all your soul and with all your mind. This is the first and great commandment. And the second is like it, you shall love your neighbor as yourself. On these two commandments hang all the law and the prophets.”</p><h3>Leader</h3><p>Are you able to keep all these things perfectly?</p><h3>Congregation</h3><p>No, truly, for by nature I am prone to the hatred of God, and of my neighbors.</p>',
                'created_at' => '2025-08-09 17:54:50',
                'updated_at' => '2025-08-09 17:54:50',
            ],
            49 => [
                'id' => 51,
                'title' => 'Be Thou My Vision (Day 16)',
                'type' => 'prayer',
                'text' => '<h3>Leader</h3><p>We praise you, O God, we acknowledge you to be the Lord. All the earth worships you, the Father everlasting. To you, all angels cry aloud, the heavens and all the powers in it. To you, cherubim and seraphim continually cry, “Holy, holy, holy, Lord God of Hosts.” Heaven and earth are full of the majesty of your glory. The glorious company of the apostles, praise you. The good fellowship of the prophets, praise you. The noble army of martyrs, praise you. The holy church throughout all the world, acknowledges you. The Father of an infinite majesty. Your honorable, true, and only Son. Also, the Holy Spirit, the Comforter.</p><p>You are the King of glory, O Christ. You are the everlasting Son of the Father. You took upon yourself to deliver man and you overcame the sharpness of death. You opened the kingdom of heaven to all believers. You sit on the right hand of God, in the glory of the Father. We believe that you will come to be our judge. We therefore pray, help your servants, whom you have redeemed with your precious blood. Make them to be numbered with your saints, in glory everlasting.</p><p>O Lord, save your people, and bless your heritage. Govern them, and lift them up forever. Day by day we magnify you. And we worship your name evermore, world without end. Grant, O Lord, to keep us this day without sin. O Lord, have mercy upon us; let your mercy shine upon us, since our trust is in you. O Lord, in you have we trusted; let us never be confounded.</p><p>Almighty God, heavenly Father, we ask you to work in us by your Holy Spirit, so that we may rightly know you, and sanctify, glorify, and praise you in all your works, in which shine forth your omnipotence, wisdom, goodness, righteousness, mercy, and truth. Grant us also that we may so direct our whole life—thoughts, words, and deeds—that your name is not blasphemed because of us, but honored and praised.</p><p>Glory be to the Father, and to the Son, and to the Holy Spirit: As it was in the beginning, is now, and ever shall be, world without end. Amen.</p>',
                'created_at' => '2025-08-09 18:00:03',
                'updated_at' => '2025-08-09 18:00:03',
            ],
            50 => [
                'id' => 52,
                'title' => 'Numbers 6:24-27',
                'type' => 'benediction',
                'text' => '<h3>Leader</h3><p>The LORD bless you and keep you; the LORD make his face to shine upon you and be gracious to you; the LORD lift up his countenance upon you and give you peace. So shall they put my name upon the people of Israel, and I will bless them.</p>',
                'created_at' => '2025-08-09 20:42:07',
                'updated_at' => '2025-08-09 20:42:19',
            ],
            51 => [
                'id' => 53,
                'title' => 'Romans 11:33-36',
                'type' => 'call-to-worship',
                'text' => '<h3>Leader</h3><p>Oh, the depth of the riches and the wisdom and the knowledge of God! How unsearchable his judgments and untraceable his ways! For who has known the mind of the Lord? Or who has been his counselor? And who has ever given to God, that he should be repaid? For from him and through him and to him are all things. To him be the glory forever. Amen.</p>',
                'created_at' => '2025-08-15 23:09:38',
                'updated_at' => '2025-08-15 23:09:38',
            ],
            52 => [
                'id' => 54,
                'title' => 'Hebrews 13:20-21',
                'type' => 'benediction',
                'text' => '<h3>Leader</h3><p>Now may the God of peace who brought again from the dead our Lord Jesus, the great shepherd of the sheep, by the blood of the eternal covenant, equip you with everything good that you may do his will, working in us that which is pleasing in his sight, through Jesus Christ, to whom be glory forever and ever. Amen.</p>',
                'created_at' => '2025-08-15 23:10:26',
                'updated_at' => '2025-08-15 23:10:26',
            ],
            53 => [
                'id' => 55,
                'title' => 'Psalm 39:7-8, 12 - O Lord, for what do I wait',
                'type' => 'confession-of-sin',
                'text' => '<h3>Congregation</h3><p>And now, O Lord, for what do I wait? My hope is in you. Deliver me from all my transgressions. Do not make me the scorn of the fool! Hear my prayer, O LORD, and give ear to my cry; hold not your peace at my tears! For I am a sojourner with you, a guest, like all my fathers.</p>',
                'created_at' => '2025-08-15 23:12:39',
                'updated_at' => '2025-08-15 23:12:39',
            ],
            54 => [
                'id' => 56,
                'title' => 'Zechariah 12:10, 13:1, 9',
                'type' => 'assurance-of-pardon',
                'text' => '<h3>Leader</h3><p>And I will pour out on the house of David and the inhabitants of Jerusalem a spirit of grace and pleas for mercy, so that, when they look on me, on him whom they have pierced, they shall mourn for him, as one mourns for an only child, and weep bitterly over him, as one weeps over a firstborn. On that day there shall be a fountain opened for the house of David and the inhabitants of Jerusalem, to cleanse them from sin and uncleanness. They will call upon my name, and I will answer them. I will say, ‘They are my people’; and they will say, ‘The LORD is my God.</p>',
                'created_at' => '2025-08-15 23:13:44',
                'updated_at' => '2025-08-15 23:13:44',
            ],
            55 => [
                'id' => 57,
                'title' => 'An Orthodox Catechism - Lord\'s Day 4: Creation and Corruption (Questions 6-8)',
                'type' => 'catechism',
                'text' => '<h3>Leader</h3><p>Did God then make man so wicked and perverse?</p><h3>Congregation</h3><p>Not so, but rather he made man good, and in his own image; that is, endowed with true righteousness and holiness, that man might rightly know God, his Creator, and heartily love him, and live with him blessed forever, and that to praise and magnify him.</p><h3>Leader</h3><p>From where then arises this wickedness of man’s nature?</p><h3>Congregation</h3><p>From the fall and disobedience of our first parents, Adam and Eve, hence is our nature so corrupt that we are all conceived and born in sin.</p><h3>Leader</h3><p>Are we so corrupt that we are not at all apt to do well, but are prone to all vice?</p><h3>Congregation</h3><p>Indeed, we are, except we be regenerated by the Holy Spirit.</p>',
                'created_at' => '2025-08-15 23:24:10',
                'updated_at' => '2025-08-15 23:24:10',
            ],
            56 => [
                'id' => 58,
                'title' => 'Be Thou My Vision (Day 11)',
                'type' => 'prayer',
                'text' => '<h3>Leader</h3><p>Almighty God, Father of all mercies, as your unworthy servants, we give you most humble and heartfelt thanks for all your goodness and loving-kindness to us and to all people. We bless you for our creation, preservation, and all the blessings of this life, but above all, for your precious love in the redemption of the world by our Lord Jesus Christ, for the means of grace, and for the hope of glory. And we pray that you would give us that due sense of all your mercies that our hearts may be sincerely thankful and that we may show forth your praise not only with our lips but in our lives, by giving up ourselves to your service and by walking before you in holiness and righteousness all our days, through Jesus Christ our Lord, to whom with you and the Holy Spirit, be all honor and glory world without end.</p><p>We pray, O God, pour out upon us your Holy Spirit—the Spirit of prayer—that we may ever love and desire to pray; being daily free to approach you, with all confidence in the name of our Lord Jesus Christ; to bow before you in every time of need, as children well beloved, O most beloved Father, you who are really a Father unto all your children in heaven and on earth.</p><p>Grant that we may always lift up unto you holy hands, without fear or doubt, and in full assurance that all our prayers and sighs which come from the heart, are truly heard. Grant also that when our help delays we shall be patient, not dictating to you either time or measure, but to wait and abide your own good time; for you have pleasure in them that fear and put their trust in your mercy.</p><p>Divine Spirit, illumine to us the words of the Lord. Show us the wealth of glory that lies beneath the old familiar stories. Teach us the depths of meaning hidden in the songs of Zion. Raise us to the heights of aspiration that is reached by the wings of the prophet. Lift us to the summit of faith that is trod by the feet of the apostle. Open our eyes, that we may behold wondrous things out of your law. Amen.</p>',
                'created_at' => '2025-08-15 23:41:36',
                'updated_at' => '2025-08-15 23:41:36',
            ],
            57 => [
                'id' => 59,
                'title' => 'Romans 9:25-26',
                'type' => 'call-to-worship',
                'text' => '<h3>Leader</h3><p>As it also says in Hosea, I will call Not My People, My People, and she who is Unloved, Beloved. And it will be in the place where they were told, you are not my people, there they will be called sons of the living God.</p>',
                'created_at' => '2025-08-23 13:28:50',
                'updated_at' => '2025-08-23 13:28:50',
            ],
            58 => [
                'id' => 60,
                'title' => 'A Dying Savior\'s Love',
                'type' => 'benediction',
                'text' => '<h3>Leader</h3><p>Now a dying Saviour’s love, a risen Saviour’s joy, an ascended Saviour’s power, and a returning Saviour’s hope, rest upon your hearts and homes.</p><h3>Congregation</h3><p>Amen.</p>',
                'created_at' => '2025-08-23 13:29:45',
                'updated_at' => '2025-08-23 13:29:45',
            ],
            59 => [
                'id' => 61,
                'title' => 'Deuteronomy 10:12-16',
                'type' => 'law',
                'text' => '<h3>Leader</h3><p>And now, Israel, what does the LORD your God require of you, but to fear the LORD your God, to walk in all his ways, to love him, to serve the LORD your God with all your heart and with all your soul, and to keep the commandments and statutes of the LORD, which I am commanding you today for your good? Behold, to the LORD your God belong heaven and the heaven of heavens, the earth with all that is in it. Yet the LORD set his heart in love on your fathers and chose their offspring after them, you above all peoples, as you are this day. Circumcise therefore the foreskin of your heart, and be no longer stubborn.</p>',
                'created_at' => '2025-08-23 13:30:36',
                'updated_at' => '2025-08-23 13:30:36',
            ],
            60 => [
                'id' => 62,
                'title' => 'Psalm 51:1-4 - Have Mercy on Me, O God',
                'type' => 'confession-of-sin',
                'text' => '<h3>Congregation</h3><p>Have mercy on me, O God, according to your steadfast love; according to your abundant mercy blot out my transgressions. Wash me thoroughly from my iniquity, and cleanse me from my sin! For I know my transgressions, and my sin is ever before me. Against you, you only, have I sinned and done what is evil in your sight, so that you may be justified in your words and blameless in your judgment.</p>',
                'created_at' => '2025-08-23 13:33:26',
                'updated_at' => '2025-08-23 13:33:26',
            ],
            61 => [
                'id' => 63,
                'title' => 'An Orthodox Catechism - Lord\'s Day 5: God\'s Justice and Mercy (Questions 9-11)',
                'type' => 'catechism',
                'text' => '<h3>Leader</h3><p>Does not God then do injustice to man, who in the law requires that of him which he is not able to perform?</p><h3>Congregation</h3><p>No, for God had made man such as he might perform it, but man, by the impulsion of the devil, and his own stubbornness, bereaved himself and all his posterity of those divine graces.</p><h3>Leader</h3><p>Does God leave this stubbornness and falling away of man unpunished?</p><h3>Congregation</h3><p>No, but is angry in a most dreadful manner, as well for the sin in which we are born, as also for those which we ourselves commit, and in most just judgement punishes them with present and everlasting punishments, as he himself pronounces, “Everyone who does not do everything written in the book of the law is cursed.”</p><h3>Leader</h3><p>Is not God then merciful?</p><h3>Congregation</h3><p>Yes, truly he is merciful, but in so, he is also just, because his justice requires that the sin committed against the divine majesty of God should also be repaid with extreme, that is, everlasting punishment, both in body and soul.</p>',
                'created_at' => '2025-08-23 16:24:14',
                'updated_at' => '2025-08-23 16:24:14',
            ],
            62 => [
                'id' => 64,
                'title' => 'Lord God, The Great and Only King',
                'type' => 'prayer',
                'text' => '<p>Lord God, The Great And Only King, you have made summer and winter, day and night; each of these revolutions serves our welfare and is full of your care and kindness.</p><p>Your bounty is seen in the relations that train us, the laws that defend us, the homes that shelter us, the food that builds us, the garments that comfort us, the continuance of our health, members, senses, understanding, memory, affection, will.</p><p>But as stars fade before the rising sun, you have eclipsed all these benefits in the wisdom and grace that purposed redemption by Jesus your Son. Blessed be your mercy that laid help on one that is mighty and willing, one that is able to save to the uttermost.</p><p>Make us deeply sensible of our need of his saving grace, of the blood that cleanses, of the rest he has promised. And impute to us that righteousness which justifies the guilty, gives them a title to eternal life, and possession of the Spirit. May we love the freeness of salvation, and joy in its holiness;</p><p>Grow our understanding of your word and your great works that we know you; Give us faith to grasp your promises, that are our hope, provide for every exigency, and prevent every evil; Keep our hearts from straying after forbidden pleasures; May your will bind all our wishes; Let us live out of the world as to its spirit, maxim, manners, but live in it as the sphere of our action and usefulness; May we be alive to every call of duty, accepting without question your determination of our circumstances and our service. Amen.</p>',
                'created_at' => '2025-08-23 16:28:17',
                'updated_at' => '2025-08-23 16:28:17',
            ],
        ]);

    }
}
