# Name of your application. Used to uniquely configure containers.
service: stave

# Name of the container image.
image: jpangborn/stave

aliases:
  shell: app exec -i --reuse bash

deploy_timeout: 60

builder:
  arch: amd64
  args:
    VITE_REVERB_APP_KEY: <%= ENV['REVERB_APP_KEY'] %>
    VITE_REVERB_HOST: reverb.stave.pangborn.cloud
    VITE_REVERB_PORT: "443"
    VITE_REVERB_SCHEME: https
  secrets:
    - COMPOSER_AUTH_JSON_BASE64

# Deploy to these servers.
servers:
  web:
    hosts:
      - 129.212.180.73
  worker:
    hosts:
      - 129.212.180.73
    cmd: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    options:
      health-cmd: "healthcheck-queue"
      health-interval: "10s"
#  reverb:
#    hosts:
#      - 129.212.180.73
#    cmd: php artisan reverb:start --host=0.0.0.0 --port=8080 --hostname=reverb.stave.pangborn.cloud
#   proxy:
#      ssl: true
#      host: reverb.stave.pangborn.cloud
#      app_port: 8080
#    options:
#      health-cmd: "healthcheck-reverb"
#      health-interval: "10s"

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: jpangborn
  password:
    - KAMAL_REGISTRY_PASSWORD

proxy:
  app_port: 8080
  host: stave.pangborn.cloud
  ssl: true
  healthcheck:
    path: /healthcheck

env:
  secret:
    - LARAVEL_ENV_ENCRYPTION_KEY
    - NIGHTWATCH_TOKEN

# Use accessory services (secrets come from .env).
accessories:
  nightwatch:
    image: laravelphp/nightwatch-agent:v1
    host: 129.212.180.73
    env:
      secret:
        - NIGHTWATCH_TOKEN
    options:
      health-cmd: "php nightwatch-status"
      health-interval: "10s"

  db:
    image: mysql:8.0
    host: 129.212.180.73
    port: 3306
    env:
      clear:
        MYSQL_ROOT_HOST: "%"
      secret:
        - MYSQL_ROOT_PASSWORD
    files:
      - database/init.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/mysql
